version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: olleflow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: olleflow-admin
      POSTGRES_PASSWORD: olleflow-admin-123
      POSTGRES_DB: olleflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
